# Generated by Django 3.2 on 2022-05-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking_time',
            field=models.CharField(choices=[('10', '10:00 AM'), ('11', '11:00 AM'), ('12', '12:00 PM'), ('1', '1:00 PM'), ('2', '2:00 PM')], max_length=50, null=True),
        ),
    ]
