# Generated by Django 3.2 on 2022-05-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0003_auto_20220521_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='person',
            field=models.IntegerField(null=True),
        ),
    ]
