# Generated by Django 3.2 on 2022-05-21 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0004_reservation_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='table_types',
            new_name='restaurents',
        ),
    ]
