# Generated by Django 3.2 on 2022-05-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0005_rename_table_types_reservation_restaurents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_time',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Restore', 'Restore')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Restore', 'Restore')], default='Pending', max_length=40),
        ),
    ]
