# Generated by Django 3.2 on 2022-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0006_auto_20220521_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_time',
            field=models.CharField(choices=[('10', '10:00 AM'), ('11', '11:00 AM'), ('12', '12:00 PM'), ('1', '1:00 PM'), ('2', '2:00 PM')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.IntegerField(),
        ),
    ]
