# Generated by Django 4.0.4 on 2022-05-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0010_rename_total_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
