# Generated by Django 4.0.4 on 2022-05-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0012_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='restaurents',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Product_App.restaurent'),
        ),
    ]
