# Generated by Django 4.0.4 on 2022-05-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_App', '0014_remove_history_product_remove_history_restaurents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='product_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
